<?php
/*
THIS CODE CHECKS THE CURRENT BROWSER URL RELATED TO THE ONE YOU DEFINE
AFTER CHEKING YOU CAN DO SOMETHING BOTH WITH POSITIVE OR NEGATIVE FEEDBACK
*/

$host = $_SERVER['SERVER_NAME'] . $_SERVER['REQUEST_URI'];

//JUST TYPE THE URL YOU WANNA CHECK WHERE IT SAYS "URL.COM/". NO NEED TO TYPE HTTP://
if($host == 'URL.COM/') {
    //IF POSITIVE, DO THIS...
    }
else {
    //IF NEGATIVE, DO THIS...
    };
?>
